version: '3.8'

services:
  todo_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://username:password@db/todo_db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"